# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('date', models.DateField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garment', models.CharField(max_length=1000)),
                ('colour', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=1000)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('feedback', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='items_purchased',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Product'),
        ),
    ]
