# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feedback',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
