# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170316_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_purchased',
        ),
        migrations.AddField(
            model_name='product',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Order'),
        ),
    ]
